### ISSUE TITLE
Do subreddit specific response

### ISSUE THREAD

**Issue by NNTin** [NNTin/Reply-Dota-2-Reddit#20]
Bot is active in /r/dota2 and /r/learndota2. Hero icons are not working in learndota2. Display hero names instead of hero icons.

**Comment by FlorianWendelborn** [comment]
Alternative solution would be to ask the mods of `/r/learndota2` to add the icons. I can imagine that they'd do that.

**Comment by NNTin** [comment]
[Bot got banned](https://i.imgur.com/mhYAVLW.png) from /r/learndota2. [It was triggering their modmail for some reason.](https://i.imgur.com/v9dXXVO.png)  
If my bot gets whitelisted I can reopen this issue. Until then one issue less.

**Comment by FlorianWendelborn** [comment]
Hmm. That's a bit odd. Good luck with sorting this out with the mods.
