### ISSUE TITLE
Include MMR and MMR eastimate for player(s)

### ISSUE THREAD

**Issue by rossengeorgiev** [NNTin/Reply-Dota-2-Reddit#21]
Easily accessible via opendota's API

`https://api.opendota.com/api/players/<account id>`

**Comment by NNTin** [comment]
Thanks for the suggestion. Post format currently looks like this: http://i.imgur.com/dat8DSw.png

Suggestions on making it prettier or is it fine?

**Comment by rossengeorgiev** [comment]
Maybe have them on a separate line, you know with double space, and have the numbers in bold. 

> Player solo MMR (powered by OpenDota): **9000 MMR**, estimate **4000 MMR**
> Analyzed a total of 0.5 matches ...

**Comment by NNTin** [comment]
Thanks. I'm updating the Reddit bot now. https://github.com/NNTin/Reply-Dota-2-Reddit/commit/8212b2707dde2f8700439b004ad974a0c6394c95

Looks like this now: https://i.imgur.com/PPouUgP.png
