### ISSUE TITLE
Underlord is reported as Spirit Breaker in comments

### ISSUE THREAD

**Issue by drusepth** [NNTin/Reply-Dota-2-Reddit#23]
See [this match](https://www.opendota.com/matches/3320215951) reported [in this comment](https://www.reddit.com/r/DotA2/comments/6nx3y8/dota_2_update_main_client_july_17_2017/dkdj6qs/). 

Underlord (the level 22 anon) is shown as Spirit Breaker in the hero column. The portrait does, however, (correctly?) link to https://www.reddit.com/hero-underlord.

Screenshot:
![untitled](https://user-images.githubusercontent.com/538235/28324671-3a6670ae-6bdc-11e7-95e8-6e33960aae41.png)

**Comment by NNTin** [comment]
Thanks for reporting. I fixed it. The dota 2 stylesheet says I need to use abyssalunderlord instead of underlord.
